var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$(document).ready(function(){});
!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):a("object"==typeof exports?require("jquery"):jQuery)}(function(a){var b,g=navigator.userAgent,h=/iphone/i.test(g),c=/chrome/i.test(g),e=/android/i.test(g);a.mask={definitions:{9:"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},autoclear:!0,dataName:"rawMaskFn",placeholder:"_"};a.fn.extend({caret:function(d,l){var k;if(0!==this.length&&!this.is(":hidden"))return"number"==typeof d?(l="number"==typeof l?l:d,this.each(function(){this.setSelectionRange?
this.setSelectionRange(d,l):this.createTextRange&&(k=this.createTextRange(),k.collapse(!0),k.moveEnd("character",l),k.moveStart("character",d),k.select())})):(this[0].setSelectionRange?(d=this[0].selectionStart,l=this[0].selectionEnd):document.selection&&document.selection.createRange&&(k=document.selection.createRange(),d=0-k.duplicate().moveStart("character",-1E5),l=d+k.text.length),{begin:d,end:l})},unmask:function(){return this.trigger("unmask")},mask:function(d,l){var k,f,m,u,z,r,x;if(!d&&0<
this.length){var w=a(this[0]);return(w=w.data(a.mask.dataName))?w():void 0}return l=a.extend({autoclear:a.mask.autoclear,placeholder:a.mask.placeholder,completed:null},l),k=a.mask.definitions,f=[],m=r=d.length,u=null,a.each(d.split(""),function(t,A){"?"==A?(r--,m=t):k[A]?(f.push(new RegExp(k[A])),null===u&&(u=f.length-1),m>t&&(z=f.length-1)):f.push(null)}),this.trigger("unmask").each(function(){function t(){if(l.completed){for(var q=u;z>=q;q++)if(f[q]&&D[q]===A(q))return;l.completed.call(v)}}function A(q){return l.placeholder.charAt(q<
l.placeholder.length?q:0)}function E(q){for(;++q<r&&!f[q];);return q}function C(q,p){if(!(0>q)){var y=q;for(p=E(p);r>y;y++)if(f[y]){if(!(r>p&&f[y].test(D[p])))break;D[y]=D[p];D[p]=A(p);p=E(p)}J();v.caret(Math.max(u,q))}}function G(q){var p,y;var B=q;for(q=A(q);r>B;B++)if(f[B]){if(p=E(B),y=D[B],D[B]=q,!(r>p&&f[p].test(y)))break;q=y}}function K(){var q=v.val(),p=v.caret();if(q.length<x.length){for(I(!0);0<p.begin&&!f[p.begin-1];)p.begin--;if(0===p.begin)for(;p.begin<u&&!f[p.begin];)p.begin++}else for(I(!0);p.begin<
r&&!f[p.begin];)p.begin++;v.caret(p.begin,p.begin);t()}function N(){I();v.val()!=M&&v.change()}function L(q,p){for(;p>q&&r>q;q++)f[q]&&(D[q]=A(q))}function J(){v.val(D.join(""))}function I(q){var p,y,B,H=v.val(),F=-1;for(B=p=0;r>p;p++)if(f[p]){for(D[p]=A(p);B++<H.length;)if(y=H.charAt(B-1),f[p].test(y)){D[p]=y;F=p;break}if(B>H.length){L(p+1,r);break}}else D[p]===H.charAt(B)&&B++,m>p&&(F=p);return q?J():m>F+1?l.autoclear||D.join("")===O?(v.val()&&v.val(""),L(0,r)):J():(J(),v.val(v.val().substring(0,
F+1))),m?p:u}var v=a(this),D=a.map(d.split(""),function(q,p){return"?"!=q?k[q]?A(p):q:void 0}),O=D.join(""),M=v.val();v.data(a.mask.dataName,function(){return a.map(D,function(q,p){return f[p]&&q!=A(p)?q:null}).join("")});v.one("unmask",function(){v.off(".mask").removeData(a.mask.dataName)}).on("focus.mask",function(){if(!v.prop("readonly")){clearTimeout(b);M=v.val();var q=I();b=setTimeout(function(){J();q==d.replace("?","").length?v.caret(0,q):v.caret(q)},10)}}).on("blur.mask",N).on("keydown.mask",
function(q){if(!v.prop("readonly")){var p=q.which||q.keyCode;x=v.val();if(8===p||46===p||h&&127===p){var y=v.caret();var B=y.begin;y=y.end;if(0===y-B){if(46!==p)for(;0<=--B&&!f[B];);else B=y=E(B-1);y=46===p?E(y):y}L(B,y);C(B,y-1);q.preventDefault()}else 13===p?N.call(this,q):27===p&&(v.val(M),v.caret(0,I()),q.preventDefault())}}).on("keypress.mask",function(q){if(!v.prop("readonly")){var p,y,B,H=q.which||q.keyCode,F=v.caret();if(!(q.ctrlKey||q.altKey||q.metaKey||32>H)&&H&&13!==H){if(0!==F.end-F.begin&&
(L(F.begin,F.end),C(F.begin,F.end-1)),p=E(F.begin-1),r>p&&(y=String.fromCharCode(H),f[p].test(y)))(G(p),D[p]=y,J(),B=E(p),e)?setTimeout(function(){a.proxy(a.fn.caret,v,B)()},0):v.caret(B),F.begin<=z&&t();q.preventDefault()}}}).on("input.mask paste.mask",function(){v.prop("readonly")||setTimeout(function(){var q=I(!0);v.caret(q);t()},0)});c&&e&&v.off("input.mask").on("input.mask",K);I()})}})});var MSCom=MSCom||{};MSCom.CMS=MSCom.CMS||{};MSCom.CMS.Mashup=MSCom.CMS.Mashup||{};
MSCom.CMS.Mashup.ContentIncludes=MSCom.CMS.Mashup.ContentIncludes||{};
MSCom.CMS.Mashup.ContentInclude2=function(a,b,g){g||(g="html");this._locale=a.attr("data-urllocale");this._url=b?b+"/"+this._locale+"/api/controls/contentinclude/"+g:window.location.protocol+"//"+window.location.host+"/"+this._locale+"/api/controls/contentinclude/"+g;this._url=$("#endpoint-svc").val();this._collection=this.getQueryValue(window.location.href,"CollectionId");this._dataaction=a.attr("data-action");this._pageId=a.attr("data-defaultPageId");this._ppaId=a.attr("data-ProgrammableContentArea");
this._host=a.attr("data-Host");this._hostsegments=a.attr("data-host-segments");this._hostquery=a.attr("data-host-querystring");this._controlAttributeMapping=a.attr("data-ControlAttributesMapping");this._action=g;if(b=a.attr("data-ajaxQuery"))this._query=JSON.parse(b);this._divToRender=a};
MSCom.CMS.Mashup.ContentInclude2.prototype={getQueryValue:function(a,b){a=(new RegExp("[\\?\x26]"+b+"\x3d([^\x26#]*)","gi")).exec(a);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))},render:function(a,b,g){var h=this._url+"?pageId\x3d"+this._pageId+"\x26host\x3d"+this._host+"\x26segments\x3d"+this._hostsegments+"\x26query\x3d"+this._hostquery;this._collection&&(h+="\x26CollectionId\x3d"+this._collection);this._dataaction&&(h+="\x26DataAction\x3d"+this._dataaction);this._ppaId&&(h+="\x26ProgrammableContentArea\x3d"+
this._ppaId);for(var c in this._query)h+="\x26"+c+"\x3d"+this._query[c];n=5;currentPath=window.location.pathname;fullPath=currentPath.substring(0,currentPath.length-n);type="sds/components/content/sdscontainer/v1/sdscontainer";h=this._url+this._query.action+"?profile\x3d606624d44113\x26ProductEditionId\x3d"+this._query.productEditionId+"\x26SKU\x3d"+this._query.skuId+"\x26friendlyFileName\x3d"+this._query.friendlyFileName+"\x26Locale\x3d"+softwareDownload.getLocale()+"\x26sessionID\x3d"+this._query.sessionId;
h={url:h,method:"GET",dataType:"json",success:function(e){null!=e&&a&&a(e)},error:function(e,d,l){b&&b(e,d,l)}};g&&(h.timeout=g);$.ajax(h)}};
(function(a,b,g){b("html").attr("data-lang",b("html").attr("lang"));b(function(){b("#download-links").attr("translate","no")});a.cascade=a.cascade||{};a.cascade.isValid=function(h){return h!==g};a.cascade.stringToBoolean=function(h){return"true"===h.toLowerCase()?!0:"false"===h.toLowerCase()?!1:null};a.cascade.evaluateRenderingCondition=function(h,c,e){h.find("[data-condition][data-conditionAssertion]").each(function(){var d=b(this).attr("data-condition"),l=b(this).attr("data-conditionAssertion");
if(d.toLowerCase().includes(c.toLowerCase())){d=d.split(".");switch(d.length){case 1:d=e;break;case 2:d=e[d[1]];break;case 3:d=e[d[1]][d[2]];break;default:d=e}d=a.cascade.isValid(d);a.cascade.stringToBoolean(l)==d?b(this).show():b(this).hide();b(this).find("#errorModalMessage").each(function(){var k="";a.cascade.isValid(e.Errors)&&0<e.Errors.length&&(b(this).empty(),e.Errors.forEach(function(f,m,u){k+=a.cascade.formatMessage(f)+"\x3cbr/\x3e"}));b(this).append(k);b(this).parents(".modal").show()})}})};
a.cascade.netResponseMessage=function(h,c,e){refId=h.getResponseHeader("X-Azure-Ref");return refId!=g&&""!=refId?"Reference ID: "+refId:""};a.cascade.formatMessage=function(h){switch(h.Key){case "ErrorSettings.SentinelReject":h=b("#msg-01").val()+a.getSession()+".";break;case "ErrorSettings.GenericError":h=b("#msg-02").val();break;default:h=b("#msg-02").val()+"\x3cbr/\x3e"+h.Value}return h};a.cascade.populateLanguages=function(h,c,e){a.cascade.evaluateRenderingCondition(h,c,e);var d=h.find("select");
d.children("option:not(:first)").remove();a.cascade.isValid(e.Skus)&&b.each(e.Skus,function(l,k){l=b("\x3coption\x3e\x3c/option\x3e").attr("value",'{"id":"'+k.Id+'","language":"'+k.Language+'"}').text(k.LocalizedLanguage);d.append(l)})};a.cascade.populateDownloadLinks=function(h,c,e){a.cascade.evaluateRenderingCondition(h,c,e);var d="";"emerald"==b("#theme-id").val()&&(d="bg-green");(textDownload=b("#text-dl").val())||(textDownload="Download");e.ProductDownloadOptions!=g&&(c=h.find("#localized-productDisplayName"),
c.empty(),c.append(e.ProductDownloadOptions[0].LocalizedProductDisplayName));e.DownloadExpirationDatetime!=g&&(c=h.find("#expiration-time"),c.empty(),c.append(e.DownloadExpirationDatetime));if(e.ProductDownloadOptions!=g){var l=h.find("#download-links");l.empty();Array.isArray(e.ProductDownloadOptions)&&e.ProductDownloadOptions.forEach(function(k,f,m){l.append('\x3cdiv\x3e\n                                        \x3cdiv\x3e\n                                            \x3ca class\x3d"btn btn-primary '+
d+'" style\x3d"margin: 0 0 1.5em 0;" href\x3d"'+k.Uri+'"\x3e\n                                                \x3cspan class\x3d"product-download-type"\x3e'+k.DownloadType+"\x3c/span\x3e "+textDownload+'\n                                            \x3c/a\x3e\n                                            \x3cinput type\x3d"hidden" class\x3d"product-download-hidden" value\x3d"{\x26quot;Name\x26quot;: \x26quot;'+k.Name+"\x26quot;,\x26quot;Uri\x26quot;: \x26quot;"+k.Uri+"\x26quot;,\x26quot;ProductDisplayName\x26quot;: \x26quot;"+
k.ProductDisplayName+"\x26quot;,\x26quot;Language\x26quot;: \x26quot;"+k.Language+"\x26quot;,\x26quot;LocalizedLanguage\x26quot;: \x26quot;"+k.LocalizedLanguage+"\x26quot;,\x26quot;LocalizedProductDisplayName\x26quot;: \x26quot;"+k.LocalizedProductDisplayName+"\x26quot;,\x26quot;DownloadType\x26quot;: "+k.DownloadType+' }"\x3e\x3c/input\x3e\n                                        \x3c/div\x3e\n                                    \x3c/div\x3e')})}};a.cascade.downloadLinksForFriendlyName=function(h,
c,e){a.cascade.evaluateRenderingCondition(h,c,e);e.ProductDownload!=g&&e.ProductDownload.Uri!=g&&(h=h.find("#download-links"),h.empty(),h.append("\n            \x3cscript\x3e\n                var softwareDownload \x3d softwareDownload || {};\n                    softwareDownload.productDownload \x3d {\n                        'uri': '"+e.ProductDownload.Uri+"',\n                        'downloadType': '"+e.ProductDownload.DownloadType+"'\n                    };\n            \x3c/script\x3e"))}})(window.softwareDownload=
window.softwareDownload||{},jQuery);
(function(a,b,g){function h(){var e=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(d){var l=(e+16*Math.random())%16|0;e=Math.floor(e/16);return("x"==d?l:l&3|8).toString(16)})}a.session=a.session||{};var c;a.session.init=function(e){var d=b("#vlsc-s-ref").val();d||(d="https://vlscppe.microsoft.com/fp/tags.js?org_id\x3d\x3cORGID\x3e\x26session_id\x3d");d=d.replace("\x3cORGID\x3e",encodeURIComponent(e));var l=b("#vlsc-i-ref").val();l||(l="https://vlscppe.microsoft.com/tags?org_id\x3d\x3cORGID\x3e\x26session_id\x3d");
l=l.replace("\x3cORGID\x3e",encodeURIComponent(e));var k=a.session.get(),f=d+k;l+=k;var m=b("#ov-df-ref").val();m||(m="https://ov-df.microsoft.com/mdt.js?instanceId\x3d560dc9f3-1aa5-4a2f-b63c-9e18f8d0e175\x26pageId\x3dsi\x26session_id\x3d");var u=m+k;d=document.createElement("input");d.id="session-id";d.type="hidden";d.value=k;e=document.createElement("script");e.type="text/javascript";e.src=f;f=document.createElement("script");f.type="text/javascript";f.src=u;b("#ov-df-inst-id").val();f=m+k;k=document.createElement("script");
k.type="text/javascript";k.src=f;f=document.createElement("noscript");m=document.createElement("iframe");m.setAttribute("class","sFrame");m.setAttribute("src",l);m.setAttribute("title","blank");f.appendChild(m);document.body.insertBefore(f,document.body.firstChild);document.body.insertBefore(e,document.body.firstChild);document.body.insertBefore(k,document.body.firstChild);document.body.insertBefore(d,document.body.firstChild);"true"===b("#table-switch").val()?a.session.directoriesTable():a.session.directoriesMwf()};
a.session.directoriesMwf=function(){var e=b("#directories"),d=b("\x3cdiv\x3e").text(b("#switch-t-action").val()||"Action").html(),l=b("\x3cdiv\x3e").text(b("#switch-t-name").val()||"Name").html(),k=b("\x3cdiv\x3e").text(b("#switch-t-domain").val()||"Domain").html(),f=b("\x3cdiv\x3e").text(b("#switch-t-id").val()||"ID").html();b("\x3cdiv\x3e").text(b("#switch-t-date").val()||"Last Used").html();var m=b("\x3cdiv\x3e").text(b("#switch-btn").val()||"Select directory").html(),u=b("\x3cdiv\x3e").text(b("#switch-cur").val()||
"Current directory").html(),z=b(".directories-selector");if(0<z.length&&0<e.length){0<e.children("input").length&&z.empty();var r=b("\x3cdiv\x3e\x3c/div\x3e");r.attr("class","row");var x=b("\x3cdiv\x3e\x3c/div\x3e");x.attr("class","col-sm-12 innerDivVertAlign");r.append(x);var w=b("\x3cdiv\x3e\x3c/div\x3e");w.attr("class","row");x.append(w);var t=b("\x3cdiv\x3e\x3c/div\x3e");t.attr("class","h6 col-sm-2");d=b("\x3cspan\x3e\x3c/span\x3e").text(d);d.attr("class","d-block d-sm-none");t.append(d);w.append(t);
t=b("\x3cdiv\x3e\x3c/div\x3e").text(l);t.attr("class","h6 col-sm-3");w.append(t);t=b("\x3cdiv\x3e\x3c/div\x3e").text(k);t.attr("class","h6 col-sm-3");w.append(t);t=b("\x3cdiv\x3e\x3c/div\x3e").text(f);t.attr("class","h6 col-sm-4");w.append(t);z.append(r);r=b("\x3cdiv\x3e\x3c/div\x3e");r.attr("class","row");x=b("\x3cdiv\x3e\x3c/div\x3e");x.attr("class","col-sm-12");r.append(x);t=b("\x3chr/\x3e");x.append(t);z.append(r);e.children("input").each(function(){r=b("\x3cdiv\x3e\x3c/div\x3e");r.attr("class",
"row");x=b("\x3cdiv\x3e\x3c/div\x3e");x.attr("class","col-sm-12 innerDivVertAlign");r.append(x);w=b("\x3cdiv\x3e\x3c/div\x3e");w.attr("class","row");x.append(w);var A="";"emerald"==b("#theme-id").val()&&(A="bg-green");if("true"==b(this).attr("data-current"))t=b('\x3cdiv\x3e\x3cspan class\x3d"dirselected"\x3e\x26#10004;\x26nbsp;'+u+"\x3c/span\x3e\x3c/div\x3e"),t.attr("class","col-sm-2");else{t=b("\x3cdiv\x3e\x3c/div\x3e");t.attr("class","col-sm-2");var E="dir_"+b("\x3cdiv\x3e").text(b(this).attr("id")).html(),
C=b("\x3cdiv\x3e").text(b(this).attr("data-user")).html(),G=b("#endpoint-switch").val();G||(G="https://www.microsoft.com/cascadeauth/sds/account/switchtenant?tenantid\x3d\x3cDIR\x3e\x26login_hint\x3d\x3cUSR\x3e\x26ru\x3d\x3cURL\x3e");C=G.replace("\x3cDIR\x3e",b("\x3cdiv\x3e").text(b(this).attr("id")).html()).replace("\x3cUSR\x3e",C).replace("\x3cURL\x3e",encodeURI(window.location.href));A=b("\x3ca\x3e",{target:"_self",href:C,"aria-label":m,id:E,class:"btn btn-primary "+A+" my-1",text:m});t.append(A)}w.append(t);
t=b("\x3cdiv\x3e\x3c/div\x3e").text(b(this).attr("value"));t.attr("class","col-sm-3");w.append(t);t=b("\x3cdiv\x3e\x3c/div\x3e").text(b(this).attr("data-domain"));t.attr("class","col-sm-3");w.append(t);t=b("\x3cdiv\x3e\x3c/div\x3e").text(b(this).attr("id"));t.attr("class","col-sm-4");w.append(t);z.append(r);r=b("\x3cdiv\x3e\x3c/div\x3e");r.attr("class","row");x=b("\x3cdiv\x3e\x3c/div\x3e");x.attr("class","col-sm-12");r.append(x);t=b("\x3chr/\x3e");x.append(t);z.append(r)})}};a.session.directoriesTable=
function(){var e=b("#directories"),d=b("\x3cdiv\x3e").text(b("#switch-t-action").val()||"").html(),l=b("\x3cdiv\x3e").text(b("#switch-t-name").val()||"Name").html(),k=b("\x3cdiv\x3e").text(b("#switch-t-domain").val()||"Domain").html(),f=b("\x3cdiv\x3e").text(b("#switch-t-id").val()||"ID").html();b("\x3cdiv\x3e").text(b("#switch-t-date").val()||"Last Used").html();var m=b("\x3cdiv\x3e").text(b("#switch-btn").val()||"Select directory").html(),u=b("\x3cdiv\x3e").text(b("#switch-cur").val()||"Current directory").html(),
z=b(".directories-selector");if(0<z.length&&0<e.length){0<e.children("input").length&&z.empty();var r="";"emerald"==b("#theme-id").val()&&(r="button-green");var x=b("\x3ctable\x3e\x3c/table\x3e").attr("class","table");var w=b("\x3ccolgroup\x3e\x3c/colgroup\x3e");w.append('\x3ccol class\x3d"dircol-action"\x3e\x3c/col\x3e');w.append('\x3ccol class\x3d"dircol-name"\x3e\x3c/col\x3e');w.append('\x3ccol class\x3d"dircol-domain"\x3e\x3c/col\x3e');w.append('\x3ccol class\x3d"dircol-id"\x3e\x3c/col\x3e');
x.append(w);w=b("\x3cthead\x3e\x3c/thead\x3e").attr("class","thead-highlight");var t=b("\x3ctbody\x3e\x3c/tbody\x3e");var A=b("\x3ctr\x3e\x3c/tr\x3e");d=b("\x3cth\x3e\x3c/th\x3e").attr("scope","col").text(d);A.append(d);d=b("\x3cth\x3e\x3c/th\x3e").attr("scope","col").text(l);A.append(d);d=b("\x3cth\x3e\x3c/th\x3e").attr("scope","col").text(k);A.append(d);d=b("\x3cth\x3e\x3c/th\x3e").attr("scope","col").text(f);A.append(d);w.append(A);x.append(w);e.children("input").each(function(){var E=b("\x3ctr\x3e\x3c/tr\x3e");
if("true"==b(this).attr("data-current"))var C=b("\x3ctd\x3e\x3c/td\x3e").append('\x3cspan class\x3d"dirselected"\x3e\x26#10004;\x26nbsp;'+u+"\x3c/span\x3e");else{C="dir_"+b("\x3cdiv\x3e").text(b(this).attr("id")).html();var G=b("\x3cdiv\x3e").text(b(this).attr("data-user")).html(),K=b("#endpoint-switch").val();K||(K="https://www.microsoft.com/cascadeauth/sds/account/switchtenant?tenantid\x3d\x3cDIR\x3e\x26login_hint\x3d\x3cUSR\x3e\x26ru\x3d\x3cURL\x3e");G=K.replace("\x3cDIR\x3e",b("\x3cdiv\x3e").text(b(this).attr("id")).html()).replace("\x3cUSR\x3e",
G).replace("\x3cURL\x3e",encodeURI(window.location.href));C=b("\x3ca\x3e",{target:"_self",href:G,"aria-label":m,id:C,class:"btn btn-primary "+r+" my-1",text:m});C=b("\x3ctd\x3e\x3c/td\x3e").append(C)}E.append(C);C=b("\x3ctd\x3e\x3c/td\x3e").text(b(this).attr("value"));E.append(C);C=b("\x3ctd\x3e\x3c/td\x3e").text(b(this).attr("data-domain"));E.append(C);C=b("\x3ctd\x3e\x3c/td\x3e").text(b(this).attr("id"));E.append(C);t.append(E)});x.append(t);z.append(x)}};a.session.get=function(){var e=b("#session-id-esi").val();
c===g&&(c=e!=g?e:h());return c}})(window.softwareDownload=window.softwareDownload||{},jQuery);
(function(a,b){a.userAttributes=a.userAttributes||{};var g=navigator.userAgent,h=[{name:"Windows 10",regex:/(Windows 10.0|Windows NT 10.0)/},{name:"Windows 8.1",regex:/(Windows 8.1|Windows NT 6.3)/},{name:"Windows 8",regex:/(Windows 8|Windows NT 6.2)/},{name:"Windows 7",regex:/(Windows 7|Windows NT 6.1)/},{name:"Windows Vista",regex:/Windows NT 6.0/},{name:"Windows Server 2003",regex:/Windows NT 5.2/},{name:"Windows XP",regex:/(Windows NT 5.1|Windows XP)/},{name:"Windows 2000",regex:/(Windows NT 5.0|Windows 2000)/},
{name:"Windows ME",regex:/(Win 9x 4.90|Windows ME)/},{name:"Windows 98",regex:/(Windows 98|Win98)/},{name:"Windows 95",regex:/(Windows 95|Win95|Windows_95)/},{name:"Windows NT 4.0",regex:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{name:"Windows CE",regex:/Windows CE/},{name:"Windows 3.11",regex:/Win16/},{name:"Android",regex:/Android/},{name:"Open BSD",regex:/OpenBSD/},{name:"Sun OS",regex:/SunOS/},{name:"Linux",regex:/(Linux|X11)/},{name:"iOS",regex:/(iPhone|iPad|iPod)/},{name:"Mac OS X",regex:/Mac OS X/},
{name:"Mac OS",regex:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{name:"QNX",regex:/QNX/},{name:"UNIX",regex:/UNIX/},{name:"BeOS",regex:/BeOS/},{name:"OS/2",regex:/OS\/2/},{name:"Search Bot",regex:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}];a.userAttributes.setUserAgent=function(c){if("string"!==typeof c)throw"value is not of type string";g=c};a.userAttributes.getUserAgent=function(){return g};a.userAttributes.getBrowser=function(){var c={name:navigator.appName,
version:""+parseFloat(navigator.appVersion),major:parseInt(navigator.appVersion,10)};-1!=(verOffset=g.indexOf("Opera"))?(c.name="Opera",c.version=g.substring(verOffset+6),-1!=(verOffset=g.indexOf("Version"))&&(c.version=g.substring(verOffset+8))):-1!=(verOffset=g.indexOf("MSIE"))?(c.name="Microsoft Internet Explorer",c.version=g.substring(verOffset+5)):-1!=(verOffset=g.indexOf("Chrome"))?(c.name="Chrome",c.version=g.substring(verOffset+7)):-1!=(verOffset=g.indexOf("Safari"))?(c.name="Safari",c.version=
g.substring(verOffset+7),-1!=(verOffset=g.indexOf("Version"))&&(c.version=g.substring(verOffset+8))):-1!=(verOffset=g.indexOf("Firefox"))?(c.name="Firefox",c.version=g.substring(verOffset+8)):-1!=g.indexOf("Trident/")?(c.name="Microsoft Internet Explorer",c.version=g.substring(g.indexOf("rv:")+3)):(nameOffset=g.lastIndexOf(" ")+1)<(verOffset=g.lastIndexOf("/"))&&(c.name=g.substring(nameOffset,verOffset),c.version=g.substring(verOffset+1),c.name.toLowerCase()==c.name.toUpperCase()&&(c.name=navigator.appName));
-1!=(ix=c.version.indexOf(";"))&&(c.version=c.version.substring(0,ix));-1!=(ix=c.version.indexOf(" "))&&(c.version=c.version.substring(0,ix));-1!=(ix=c.version.indexOf(")"))&&(c.version=c.version.substring(0,ix));c.major=parseInt(""+c.version,10);isNaN(c.major)&&(c.version=""+parseFloat(navigator.appVersion),c.major=parseInt(navigator.appVersion,10));return c};a.userAttributes.getCpu=function(){var c={architecture:""};/WOW64|Win64|amd64/.test(g)?c.architecture="x64":c.architecture="";return c};a.userAttributes.getOs=
function(){var c={name:"",version:""};for(d in h){var e=h[d];if(e.regex.test(g)){c.name=e.name;break}}/Windows/.test(c.name)&&(c.version=/Windows (.*)/.exec(c.name)[1],c.name="Windows");var d=null;switch(c.name){case "Mac OS X":d=/Mac OS X (10[\._\d]+)/.exec(g);c.version=null==d?"":d[1];break;case "Android":d=/Android(-| )([\._\d]+)/.exec(g);c.version=null==d?"":d[1];break;case "iOS":c.version=/OS (\d+)_(\d+)_?(\d+)?/.exec(g),c.version=null==d?"":c.version[1]+"."+c.version[2]+"."+(c.version[3]|0)}return c}})(window.softwareDownload=
window.softwareDownload||{});
(function(a,b,g){function h(f){if(!l.hasOwnProperty(f))throw"View '"+f+"' not found.";return l[f]}function c(f,m){m?(b(f).parent().show(),b(f).show()):b(f).parent().hide()}function e(f,m){m.forEach(function(u){f.hasOwnProperty(u)||(f[u]=u)})}a.navigation=a.navigation||{};var d={},l={},k={showOnly:!1};a.navigation.addView=function(f){e(d,f.selectors);if(f.name!==g&&!l.hasOwnProperty(f.name)){var m=f.name,u=f.options,z={},r;for(r in k)z[r]=u!==g&&u.hasOwnProperty(r)?u[r]:k[r];l[m]={selectors:{},options:z};
e(l[f.name].selectors,f.selectors)}};a.navigation.showView=function(f){f=h(f);if(f.options.showOnly)for(var m in f.selectors)c(m,!0);else for(m in d)f.selectors[m]===g?c(m,!1):c(m,!0)};a.navigation.addToView=function(f){var m=h(f.name);e(d,f.selectors);e(m.selectors,f.selectors)};a.navigation.addToAllViews=function(f){e(d,f);for(var m in l)l.hasOwnProperty(m)&&e(l[m].selectors,f)}})(window.softwareDownload=window.softwareDownload||{},jQuery);
(function(a,b,g){function h(k){for(var f,m=999,u=d.length-1;0<=u;u--){var z=e(d[u].locales,k.locale),r=e(d[u].pages,k.page),x=0!=d[u].locales.length,w=0!=d[u].pages.length;if(r&&z)return d[u];1<m&&r&&!x?(f=d[u],m=1):2<m&&z&&!w?(f=d[u],m=2):3<m&&!w&&!x&&(f=d[u],m=3)}return f}function c(k,f){if(k===g){k="";var m=window.location.pathname.split("/");1<m.length&&(k=m[1])}if(f===g)a:{f=window.location.pathname.split("/");for(m=f.length-1;0<=m;m--)if(""!==f[m]){f=f[m];break a}f=""}return{locale:k,page:f}}
function e(k,f){return k.some(function(m){return m.toLowerCase()===f.toLowerCase()})}a.siteConfiguration=a.siteConfiguration||{};var d=[],l={version:"",orgId:"",locales:[],pages:[]};a.siteConfiguration.add=function(k){var f={},m;for(m in l)f[m]=k!==g&&k.hasOwnProperty(m)?k[m]:l[m];d.push(f)};a.siteConfiguration.getVersion=function(k,f){k=c(k,f);return h(k).version};a.siteConfiguration.getOrgId=function(k,f){k=c(k,f);return h(k).orgId}})(window.softwareDownload=window.softwareDownload||{},jQuery);
(function(a,b,g){function h(c){c=c.split("/");for(var e=c.length-1;0<=e;e--)if(""!==c[e])return c[e];return""}a.pageType={unknown:"unknown",other:"other",wip:"wip",localePicker:"localePicker",systembuilder:"systembuilder",dac:"dac",Win10NRS3FeaturePack:"Win10NRS3FeaturePack"};a.eventTarget=null;a.setDownloadTypeText=function(){b(".product-download-type").each(function(){var c=b(this).text(),e=b("#dlt-00").val();e||(e="32-bit");var d=b("#dlt-01").val();d||(d="64-bit");var l=b("#dlt-0d").val();l||(l=
"Download Now");"0"==c||"isox86"==c.toLowerCase()?b(this).text(e):"1"==c||"isox64"==c.toLowerCase()?b(this).text(d):b(this).parent().text(l)})};a.isValidProductKey=function(){return/[\w\d]{5}-[\w\d]{5}-[\w\d]{5}-[\w\d]{5}-[\w\d]{5}/.test(b("#pk-input-key").val())};a.getValueOrNull=function(c){c=b(c).val();return"null"==c||""==c||null==c?null:c};a.configureViews=function(){a.navigation.addView({name:"homePage",selectors:"#SoftwareDownload_Introduction #SoftwareDownload_DownloadSteps #SoftwareDownload_KeyEntry #SoftwareDownload_EditionNotes #SoftwareDownload_EditionSelection #SoftwareDownload_EditionSelection2".split(" ")});
a.navigation.addView({name:"productKeyLanguage",selectors:["#SoftwareDownload_Introduction","#SoftwareDownload_DownloadSteps","#SoftwareDownload_KeyEntry","#SoftwareDownload_LanguageSelectionByKey"]});a.navigation.addView({name:"productEditionLanguage_a",selectors:["#SoftwareDownload_Introduction","#SoftwareDownload_EditionNotes","#SoftwareDownload_EditionSelection","#SoftwareDownload_EditionSelection2","#SDS_LanguageSelectionByProductEdition_a"]});a.navigation.addView({name:"productEditionLanguage_b",
selectors:["#SoftwareDownload_Introduction","#SoftwareDownload_EditionNotes","#SoftwareDownload_EditionSelection","#SoftwareDownload_EditionSelection2","#SDS_LanguageSelectionByProductEdition_b"]});a.navigation.addView({name:"productEditionLanguage",selectors:"#SoftwareDownload_Introduction #SoftwareDownload_EditionNotes #SoftwareDownload_EditionSelection #SoftwareDownload_EditionSelection2 #SDS_LanguageSelectionByProductEdition #SDS_LanguageSelectionByProductEdition_arm".split(" ")});a.navigation.addView({name:"productEditionLanguage2",
selectors:["#SoftwareDownload_Introduction","#SoftwareDownload_EditionNotes","#SoftwareDownload_EditionSelection","#SoftwareDownload_EditionSelection2","#SDS_LanguageSelectionByProductEdition2"]});a.navigation.addView({name:"productDownload_a",selectors:["#SoftwareDownload_DownloadLinks_a","#SoftwareDownload_Email","#SoftwareDownload_Feedback"]});a.navigation.addView({name:"productDownload_b",selectors:["#SoftwareDownload_DownloadLinks_b","#SoftwareDownload_Email","#SoftwareDownload_Feedback"]});
a.navigation.addView({name:"productDownload",selectors:["#SoftwareDownload_DownloadLinks","#SoftwareDownload_DownloadLinkData","#SoftwareDownload_Email","#SoftwareDownload_Feedback"]});a.navigation.addView({name:"productDownloadError",selectors:["#SoftwareDownload_DownloadLinks","#SoftwareDownload_DownloadLinkData","#SoftwareDownload_DownloadLinks_a","#SoftwareDownload_DownloadLinks_b"],options:{showOnly:!0}});a.navigation.addView({selectors:["#windows10-topBanner"]});var c=a.userAttributes.getOs();
"windows"==c.name.toLowerCase()&&"10"==c.version&&a.navigation.addToAllViews(["#windows10-topBanner"])};a.getKey=function(){return b("#pk-input-key").val()};a.getSession=function(){return b("#session-id").val()};a.getLocale1=function(){var c="",e=window.location.pathname.split("/");1<e.length&&(c=e[1]);return c};a.getLocale=function(){var c="en-us",e=b("html").attr("data-lang");e!=g&&(c=e);return c};a.progressModalIsVisible=function(c){var e=b("#progress-modal");c?e.show():e.hide()};a.getPageName=
function(c){var e="";(c="undefined"!==typeof c?c:window.location.pathname)&&(c=h(c))&&(e=c.split("?",1));return e};a.getPageType=function(c){if("undefined"===typeof c||null==c)return a.pageType.unknown;switch(c.toString().toLowerCase()){case "faq":case "home":case "office":case "vlacademic":case "vlacademiciso":case "vlacademicoffice":case "vlacademicwindows10":case "vlacademicwindows10iso":case "windows10":case "windows10iso":case "windows10startfresh":case "windows7":case "windows8":case "windows8iso":return a.pageType.other;
case "windowsinsiderpreviewadk":case "windowsinsiderpreviewadvanced":case "windowsinsiderpreviewhlk":case "windowsinsiderpreviewiso":case "windowsinsiderpreviewsdk":case "windowsinsiderpreviewwdk":case "windowsinsiderpreviewserver":case "windowsiot":case "windows10iotcore":return a.pageType.wip;case "locale":return a.pageType.localePicker;case "systembuilder":return a.pageType.systembuilder;case "dac":case "windowsinsiderpreviewdac":return a.pageType.dac;case "mediafeaturepack":return a.pageType.Win10NRS3FeaturePack;
default:return a.pageType.unknown}};a.getUserDetails=function(){var c=null;if(0<b("#signedin-user-details").length){c=JSON.parse(b("#signedin-user-details").val());var e=a.getPageName();c=JSON.stringify({FirstName:c.FirstName,LastName:c.LastName,Puid:c.Puid,Cid:c.Cid,PageName:e})}return c};a.systemBuilderAttestationModalIsVisible=function(c){var e=b("#Systembuilder_Attestation"),d=b("#SoftwareDownload_EditionSelection");c?(e.show(),d.hide()):(e.hide(),d.show())};a.renderContent=function(c){var e=
c.errorHandler;a.eventTarget=c.target;if(c.showProgress!==g&&c.showProgress){a.progressModalIsVisible(!0);var d=function(f){c.callback(f);a.progressModalIsVisible(!1)}}else d=c.callback;if("undefined"!==typeof a.siteConfiguration){var l=h(window.location.pathname),k=a.getLocale();c.query.sdVersion=a.siteConfiguration.getVersion(k,l)}l=b("#"+c.id);l.attr("data-ajaxQuery",JSON.stringify(c.query));l.attr("data-defaultpageid");(new MSCom.CMS.Mashup.ContentInclude2(l)).render(d,e)};a.renderContent1=function(c){alert("inside renderContent1");
a.eventTarget=c.target;if(c.showProgress!==g&&c.showProgress){alert("entering callback1");a.progressModalIsVisible(!0);alert("entering callback2");var e=function(){alert("before calling callback1");c.callback();a.progressModalIsVisible(!1)}}else alert("before calling callback2"),e=c.callback;alert("after calling callback1");if("undefined"!==typeof a.siteConfiguration){var d=h(window.location.pathname),l=a.getLocale();c.query.sdVersion=a.siteConfiguration.getVersion(l,d)}alert("after calling callback2");
d=b("#"+c.id);d.attr("data-ajaxQuery",JSON.stringify(c.query));alert(d);alert(JSON.stringify(c.query));alert("after calling callback3");l=d.attr("data-defaultpageid");alert(l);alert("after calling callback4");MSCom.CMS.Mashup.ContentIncludes["_"+l]=new MSCom.CMS.Mashup.ContentInclude2(d);alert("after calling callback5");MSCom.CMS.Mashup.ContentIncludes["_"+l].render(e);alert("after calling callback6")};a.configureSite=function(){a.siteConfiguration.add({version:"2",orgId:"y6jn8c31"})};a.parseErrorMessage=
function(){var c="";"undefined"!==typeof a.siteConfiguration&&(c=a.siteConfiguration.getVersion());"2"==c&&(c=b("#errorModalMessage"),/715-123130|123130-715/.test(c.text())&&c.append(" "+a.getSession()+"."))};a.parseProductDownload=function(c){0<b("#card-info-content").length?(a.setDownloadTypeText(),a.navigation.showView(c)):a.navigation.showView("productDownloadError")};a.setReferrerLinks=function(c){"undefined"!==typeof c&&b(".mscom-link").each(function(){var e=b(this),d=e.attr("href")+c;e.attr("href",
d)})};a.setReferrerPage=function(){var c=document.referrer;if(c){var e=a.getPageName(c);switch(a.getPageType(e)){case a.pageType.other:case a.pageType.localePicker:a.setReferrerLinks(e);break;case a.pageType.wip:case a.pageType.systembuilder:case a.pageType.dac:case a.pageType.Win10NRS3FeaturePack:b("body").hide(),alert("This page is only available in English."),window.location.replace(c)}}};a.LogWipUserDetails=function(){if(0<b("#user-not-signedin").length){var c=a.AppInsights.getCustomEventProperties("UserIsNotSignedInLandedOnWipPage",
a.getLocale(),a.getSession(),JSON.stringify({PageName:a.getPageName()}));a.AppInsights.getAppInsights().trackEvent("Request",c)}else 0<b("#user-signedin-not-insider").length?(c=a.AppInsights.getCustomEventProperties("UserIsSignedInButNotInsider",a.getLocale(),a.getSession(),a.getUserDetails()),a.AppInsights.getAppInsights().trackEvent("Request",c)):0<b("#windowsinsideriso-extras").length&&(c=a.AppInsights.getCustomEventProperties("UserIsValidWindowsInsider",a.getLocale(),a.getSession(),a.getUserDetails()),
a.AppInsights.getAppInsights().trackEvent("Request",c))};a.LogDpcUserDetails=function(){if(0<b("#user-not-signedin").length){var c=a.AppInsights.getCustomEventProperties("UserIsNotSignedInLandedOnDpcPage",a.getLocale(),a.getSession(),JSON.stringify({PageName:a.getPageName()}));a.AppInsights.getAppInsights().trackEvent("Request",c)}else 0<b("#user-signedin-not-dpcUser").length?(c=a.AppInsights.getCustomEventProperties("UserIsSignedInButNotDpcUser",a.getLocale(),a.getSession(),a.getUserDetails()),a.AppInsights.getAppInsights().trackEvent("Request",
c)):0<b("#dpcuser-notsigned-confidentiality").length?(c=a.AppInsights.getCustomEventProperties("DpcUserIsSignedInButNotSignedConfidentialityClause",a.getLocale(),a.getSession(),a.getUserDetails()),a.AppInsights.getAppInsights().trackEvent("Request",c)):0<b("#dpcuser-nothaving-validstatus").length?(c=a.AppInsights.getCustomEventProperties("DpcUserIsSignedInButNotHavingValidStatus",a.getLocale(),a.getSession(),a.getUserDetails()),a.AppInsights.getAppInsights().trackEvent("Request",c)):0<b("#Systembuilder_Introduction").length&&
(c=a.AppInsights.getCustomEventProperties("UserIsValidDpcUser",a.getLocale(),a.getSession(),a.getUserDetails()),a.AppInsights.getAppInsights().trackEvent("Request",c))};a.showError=function(c,e,d,l){c?(b(e).addClass("has-error"),b(d).attr("aria-describedby",l),b(d).attr("aria-invalid","true"),b(d).focus()):(b(e).removeClass("has-error"),b(d).removeAttr("aria-describedby"),b(d).attr("aria-invalid","false"))};a.parseSystemBuilderAttestation=function(){0<b("#Systembuilder_Introduction").length&&(b("#systembuilder_attestation_chkbox").prop("checked",
!1),b("#systembuilder_attestation_confirm").prop("disabled",!0),a.systemBuilderAttestationModalIsVisible(!0))};a.checkSystemBuilderAttestation=function(){var c=a.getPageName();a.getPageType(c)==a.pageType.systembuilder&&0==b("#systembuilder_attestation_chkbox").prop("checked")&&(c=a.AppInsights.getCustomEventProperties("DpcUserNotSignedTheAttestationBox",a.getLocale(),a.getSession(),JSON.stringify({PageName:a.getPageName()})),a.AppInsights.getAppInsights().trackEvent("Request",c),alert("Accept the terms and conditions to continue."),
window.location.reload(!0))}})(window.softwareDownload=window.softwareDownload||{},jQuery);
$(function(){softwareDownload.configureSite();softwareDownload.session.init(softwareDownload.siteConfiguration.getOrgId());softwareDownload.configureViews();softwareDownload.navigation.showView("homePage");"undefined"!==typeof softwareDownload.redirection?(softwareDownload.redirection.redirect(),!1===softwareDownload.redirection.isRedirecting&&$("body").addClass("loaded")):$("body").addClass("loaded");$("#pk-input-key").mask("?*****-*****-*****-*****-*****",{placeholder:" "});softwareDownload.AppInsights.getAppInsights().trackPageView(null,
null,{Locale:softwareDownload.getLocale()});var a=softwareDownload.getPageName();switch(softwareDownload.getPageType(a)){case softwareDownload.pageType.wip:softwareDownload.LogWipUserDetails();break;case softwareDownload.pageType.localePicker:softwareDownload.setReferrerPage();break;case softwareDownload.pageType.systembuilder:softwareDownload.parseSystemBuilderAttestation(),softwareDownload.LogDpcUserDetails()}if(!(0<$(".glyph_aadAccount_circle").length||0<$(".glyph_account_circle").length)&&(0<
$("#user-not-signedin").length||0<$("#devcenter-user-not-signedin").length))var b=setInterval(function(){if(0<$(".glyph_aadAccount_circle").length||0<$(".glyph_account_circle").length){if(0<$("#user-not-signedin").length||0<$("#devcenter-user-not-signedin").length)softwareDownload.progressModalIsVisible(!0),location.reload(!0);clearInterval(b)}},250)});
$(function(){function a(g){g?$(document).unbind("keydown mousewheel DOMMouseScroll"):$(document).bind("keydown mousewheel DOMMouseScroll",function(h){h.preventDefault()})}function b(){$(document).bind("keydown mousewheel DOMMouseScroll",function(g){var h=window.event?g.which:g.keyCode;9==h?(g.preventDefault(),$(".modal-dismiss").is(":focus")?$("#faq").focus():$(".modal-dismiss").focus()):13!=h&&g.preventDefault()})}$(".modal").bind("DOMAttrModified",function(){$(".modal").is(":visible")?0<$(".modal-dismiss").length?
(a(!0),$(".modal-dismiss").focus(),b()):a(!1):a(!0)})});
$(function(){window.onload=function(){window.dfp.doFpt(this.document)};$(document).on("click","#windows10-upgrade-now",function(){var a=softwareDownload.AppInsights.getCustomEventProperties("Windows10UpgradeNowClick",softwareDownload.getLocale(),softwareDownload.getSession());softwareDownload.AppInsights.getAppInsights().trackEvent("Request",a)});$(document).on("click","#windows10-downloadtool-now",function(){var a=softwareDownload.AppInsights.getCustomEventProperties("Windows10MctDownloadClick",softwareDownload.getLocale(),
softwareDownload.getSession());softwareDownload.AppInsights.getAppInsights().trackEvent("Request",a)});$(document).on("click","#windows8-downloadtool-now",function(){var a=softwareDownload.AppInsights.getCustomEventProperties("Windows8MctDownloadClick",softwareDownload.getLocale(),softwareDownload.getSession());softwareDownload.AppInsights.getAppInsights().trackEvent("Request",a)});$(document).on("click","#vlap-downloadtool-now",function(){var a=softwareDownload.AppInsights.getCustomEventProperties("VlapMctDownloadClick",
softwareDownload.getLocale(),softwareDownload.getSession());softwareDownload.AppInsights.getAppInsights().trackEvent("Request",a)});$(document).on("click","#user-not-signedin",function(){var a=softwareDownload.AppInsights.getCustomEventProperties("UserIsNotSignedInClickedOnWipSignUpPage",softwareDownload.getLocale(),softwareDownload.getSession(),JSON.stringify({PageName:softwareDownload.getPageName()}));softwareDownload.AppInsights.getAppInsights().trackEvent("Request",a)});$(document).on("click",
"#user-signedin-not-insider",function(){var a=softwareDownload.AppInsights.getCustomEventProperties("UserIsSignedInButNotInsiderClickedOnWipSignUpPage",softwareDownload.getLocale(),softwareDownload.getSession(),softwareDownload.getUserDetails());softwareDownload.AppInsights.getAppInsights().trackEvent("Request",a)});$(document).on("click","#systembuilder-extra-download",function(){$("#product-edition").prop("selectedIndex",0);softwareDownload.navigation.showView("homePage")});$(document).on("click",
"#systembuilder_attestation_chkbox",function(){$("#systembuilder_attestation_chkbox").prop("checked")?($("#systembuilder_attestation_confirm").prop("disabled",!1),$("#systembuilder_attestation_confirm").addClass("button-blue")):($("#systembuilder_attestation_confirm").prop("disabled",!0),$("#systembuilder_attestation_confirm").removeClass("button-blue"))});$(document).on("click","#systembuilder_attestation_confirm",function(){$("#systembuilder_attestation_chkbox").prop("checked")&&softwareDownload.systemBuilderAttestationModalIsVisible(!1)});
$(document).on("click","#submit-key",function(){softwareDownload.isValidProductKey()?(softwareDownload.showError(!1,"#pk-input-validation","#pk-input-key","pk-input-key-error"),nodeId="SoftwareDownload_LanguageSelectionByKey",actionName="GetSkuInformationByKey",viewName="productKeyLanguage",softwareDownload.renderContent({id:nodeId,query:{action:actionName,key:softwareDownload.getKey(),sessionId:softwareDownload.getSession()},callback:function(a){softwareDownload.parseErrorMessage();softwareDownload.navigation.showView(viewName)},
showProgress:!0,target:$(this),errorHandler:function(a,b,g){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(a,b,g),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName)}}),$("html,body").animate({scrollTop:$("#submit-key").offset().top})):softwareDownload.showError(!0,"#pk-input-validation","#pk-input-key",
"pk-input-key-error")});$(document).on("click","#submit-sku",function(){var a=$("#product-languages").val();"null"==a?softwareDownload.showError(!0,"#pk-language-validation","#product-languages","product-languages-error"):(softwareDownload.showError(!1,"#pk-language-validation","#product-languages","product-languages-error"),softwareDownload.checkSystemBuilderAttestation(),a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks",actionName="GetProductDownloadLinksBySku",viewName="productDownload",
softwareDownload.renderContent({id:nodeId,query:{action:actionName,key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),skuId:a.id,language:a.language},callback:function(b){softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName);$("html,body").animate({scrollTop:$("#SoftwareDownload_DownloadLinks").offset().top})},showProgress:!0,
target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});$(document).on("click","#submit-sku-a",function(){var a=$("#product-languages_a").val();"null"==
a?softwareDownload.showError(!0,"#pk-language-validation","#product-languages","product-languages-error"):(softwareDownload.showError(!1,"#pk-language-validation","#product-languages","product-languages-error"),softwareDownload.checkSystemBuilderAttestation(),a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks_a",actionName="GetProductDownloadLinksBySku",viewName="productDownload_a",softwareDownload.renderContent({id:nodeId,query:{action:actionName,key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),
skuId:a.id,language:a.language},callback:function(b){softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName);$("html,body").animate({scrollTop:$("#SoftwareDownload_DownloadLinks_a").offset().top})},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+
nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});$(document).on("click","#submit-sku-b",function(){var a=$("#product-languages_b").val();"null"==a?softwareDownload.showError(!0,"#pk-language-validation","#product-languages","product-languages-error"):(softwareDownload.showError(!1,"#pk-language-validation",
"#product-languages","product-languages-error"),softwareDownload.checkSystemBuilderAttestation(),a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks_b",actionName="GetProductDownloadLinksBySku",viewName="productDownload_b",softwareDownload.renderContent({id:"SoftwareDownload_DownloadLinks_b",query:{action:"GetProductDownloadLinksBySku",key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),skuId:a.id,language:a.language},callback:function(b){softwareDownload.cascade.populateDownloadLinks($("#"+
nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName);$("html,body").animate({scrollTop:$("#SoftwareDownload_DownloadLinks_b").offset().top})},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,
g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});$(document).on("click","#submit-sku-arm",function(){var a=$("#product-languages").val();"null"==a?softwareDownload.showError(!0,"#pk-language-validation","#product-languages","product-languages-error"):(softwareDownload.showError(!1,"#pk-language-validation","#product-languages","product-languages-error"),softwareDownload.checkSystemBuilderAttestation(),
a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks_WithCrcHash11_Arm",actionName="GetProductDownloadLinksBySku",viewName="productDownload_b",softwareDownload.renderContent({id:nodeId,query:{action:actionName,key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),skuId:a.id,language:a.language},callback:function(b){softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName);
$("html,body").animate({scrollTop:$("#SoftwareDownload_DownloadLinks").offset().top})},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});
$(document).on("click","#submit-sku2",function(){var a=$("#product-languages2").val();"null"==a?softwareDownload.showError(!0,"#pk-language2-validation","#product-languages2","product-languages2-error"):(softwareDownload.showError(!1,"#pk-language2-validation","#product-languages2","product-languages2-error"),softwareDownload.checkSystemBuilderAttestation(),a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks",actionName="GetProductDownloadLinksBySku",viewName="",softwareDownload.renderContent({id:nodeId,
query:{action:actionName,key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),skuId:a.id,language:a.language},callback:function(b){softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload();$("html,body").animate({scrollTop:$("#SoftwareDownload_DownloadLinks").offset().top})},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+
nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});$(document).on("change","#product-languages",function(){softwareDownload.xbox.xboxIconsPresent()&&(softwareDownload.navigation.showView("productEditionLanguage"),softwareDownload.xbox.resetToTwo())});$(document).on("click","#submit-sku3",
function(){var a=$("#product-languages").val();"null"==a?softwareDownload.showError(!0,"#pk-language-validation","#product-languages","product-languages-error"):(softwareDownload.showError(!1,"#pk-language-validation","#product-languages","product-languages-error"),softwareDownload.checkSystemBuilderAttestation(),a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks",actionName="GetProductDownloadLinksBySku",viewName="productDownload",softwareDownload.renderContent({id:nodeId,query:{action:actionName,
key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),skuId:a.id,language:encodeURI(a.language)},callback:function(b){softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName);$("#linkGdk_download").focus();softwareDownload.xbox.xboxIconsPresent()&&softwareDownload.xbox.resetToThree();$("html,body").animate({scrollTop:$("#SoftwareDownload_DownloadLinks").offset().top})},
showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});$(document).on("click","#submit-sku4",function(){var a=$("#product-languages").val();
"null"==a?softwareDownload.showError(!0,"#pk-language-validation","#product-languages","product-languages-error"):(softwareDownload.showError(!1,"#pk-language-validation","#product-languages","product-languages-error"),softwareDownload.checkSystemBuilderAttestation(),a=JSON.parse(a),nodeId="SoftwareDownload_DownloadLinks",actionName="GetProductDownloadLinksBySku",viewName="",softwareDownload.renderContent({id:nodeId,query:{action:actionName,key:softwareDownload.getKey(),sessionId:softwareDownload.getSession(),
skuId:a.id,language:a.language},callback:function(b){softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload();$("html,body").animate({scrollTop:$("#SoftwareDownload_WindowsServer_DownloadLinks").offset().top})},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateDownloadLinks($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,
g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.parseErrorMessage();softwareDownload.parseProductDownload(viewName)}}))});$(document).on("change","#product-edition",function(){softwareDownload.navigation.showView("homePage");softwareDownload.xbox.resetToOne()});$(document).on("click","#submit-product-edition",function(){var a=softwareDownload.getValueOrNull("#product-edition");null==a?softwareDownload.showError(!0,"#productEdition-validation","#product-edition","product-edition-error"):
(softwareDownload.showError(!1,"#productEdition-validation","#product-edition","product-edition-error"),softwareDownload.checkSystemBuilderAttestation(),nodeId="SDS_LanguageSelectionByProductEdition",actionName="getskuinformationbyproductedition",viewName="productEditionLanguage",softwareDownload.renderContent({id:nodeId,query:{action:actionName,sessionId:softwareDownload.getSession(),productEditionId:a},callback:function(b){softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();
softwareDownload.navigation.showView(viewName);$("#product-languages").focus();softwareDownload.xbox.xboxIconsPresent()&&softwareDownload.xbox.resetToTwo()},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName)}}),
$("html,body").animate({scrollTop:$("#product-edition").offset().top}))});$(document).on("click","#submit-product-edition-a",function(){var a=softwareDownload.getValueOrNull("#product-edition-a");null==a?softwareDownload.showError(!0,"#productEdition-validation-a","#product-edition-a","product-edition-error-a"):(softwareDownload.showError(!1,"#productEdition-validation-a","#product-edition-a","product-edition-error-a"),softwareDownload.checkSystemBuilderAttestation(),nodeId="SDS_LanguageSelectionByProductEdition_a",
actionName="getskuinformationbyproductedition",viewName="productEditionLanguage_a",softwareDownload.renderContent({id:nodeId,query:{action:actionName,sessionId:softwareDownload.getSession(),productEditionId:a},callback:function(b){softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName);$("#product-languages_a").focus();softwareDownload.xbox.xboxIconsPresent()&&softwareDownload.xbox.resetToTwo()},
showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName)}}),$("html,body").animate({scrollTop:$("#product-edition-a").offset().top}))});$(document).on("click","#submit-product-edition-b",
function(){var a=softwareDownload.getValueOrNull("#product-edition-b");null==a?softwareDownload.showError(!0,"#productEdition-validation-b","#product-edition-b","product-edition-error-b"):(softwareDownload.showError(!1,"#productEdition-validation-b","#product-edition-b","product-edition-error-b"),softwareDownload.checkSystemBuilderAttestation(),nodeId="SDS_LanguageSelectionByProductEdition_b",actionName="getskuinformationbyproductedition",viewName="productEditionLanguage_b",softwareDownload.renderContent({id:nodeId,
query:{action:actionName,sessionId:softwareDownload.getSession(),productEditionId:a},callback:function(b){softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName);$("#product-languages_b").focus();softwareDownload.xbox.xboxIconsPresent()&&softwareDownload.xbox.resetToTwo()},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateLanguages($("#"+
nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName)}}),$("html,body").animate({scrollTop:$("#product-edition-b").offset().top}))});$(document).on("click","#submit-product-edition-arm",function(){var a=softwareDownload.getValueOrNull("#product-edition-arm");null==a?softwareDownload.showError(!0,"#productEdition-validation-arm","#product-edition-arm",
"product-edition-error-arm"):(softwareDownload.showError(!1,"#productEdition-validation-arm","#product-edition-arm","product-edition-error-arm"),softwareDownload.checkSystemBuilderAttestation(),nodeId="SDS_LanguageSelectionByProductEdition_arm",actionName="getskuinformationbyproductedition",viewName="productEditionLanguage",softwareDownload.renderContent({id:nodeId,query:{action:actionName,sessionId:softwareDownload.getSession(),productEditionId:a},callback:function(b){softwareDownload.cascade.populateLanguages($("#"+
nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName);softwareDownload.xbox.xboxIconsPresent()&&softwareDownload.xbox.resetToTwo()},showProgress:!0,target:$(this),errorHandler:function(b,g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();
softwareDownload.navigation.showView(viewName)}}),$("html,body").animate({scrollTop:$("#product-edition-arm").offset().top}))});$(document).on("click","#submit-product-edition2",function(){var a=softwareDownload.getValueOrNull("#product-edition2");null==a?softwareDownload.showError(!0,"#productEdition2-validation","#product-edition2","product-edition2-error"):(softwareDownload.showError(!1,"#productEdition2-validation","#product-edition2","product-edition2-error"),softwareDownload.checkSystemBuilderAttestation(),
nodeId="SDS_LanguageSelectionByProductEdition2",actionName="getskuinformationbyproductedition",viewName="productEditionLanguage2",softwareDownload.renderContent({id:nodeId,query:{action:actionName,sessionId:softwareDownload.getSession(),productEditionId:a},callback:function(b){softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,b);softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName)},showProgress:!0,target:$(this),errorHandler:function(b,
g,h){softwareDownload.progressModalIsVisible(!1);softwareDownload.cascade.populateLanguages($("#"+nodeId),actionName,{Errors:[{Key:"ErrorSettings.Network",Value:softwareDownload.cascade.netResponseMessage(b,g,h),Type:0}]});softwareDownload.checkSystemBuilderAttestation();softwareDownload.navigation.showView(viewName)}}),$("html,body").animate({scrollTop:$("#product-edition2").offset().top}))});$(document).on("click",".submit-friendlyFileName",function(){var a=JSON.parse(this.dataset.swdlDownload);
nodeId="SoftwareDownload_DownloadLinkData";actionName="GetProductDownloadLinkForFriendlyFileName";softwareDownload.renderContent({id:nodeId,query:{action:actionName,sessionId:softwareDownload.getSession(),friendlyFileName:a.friendlyFileName},callback:function(b){softwareDownload.cascade.downloadLinksForFriendlyName($("#"+nodeId),actionName,b);softwareDownload.parseErrorMessage();void 0!=softwareDownload.productDownload&&""!=softwareDownload.productDownload.uri&&(window.location.href=softwareDownload.productDownload.uri);
softwareDownload.parseProductDownload("productDownload")},showProgress:!0,target:$(this)})});$(document).on("click",".submit-friendlyFileName1",function(){JSON.parse(this.dataset.swdlDownload);alert("in");alert("incheck");softwareDownload.renderContent1({id:"SoftwareDownload_DownloadLinkData",query:{action:"GetProductDownloadLinkForFriendlyFileName"},callback:function(a){alert("callback");softwareDownload.parseErrorMessage();void 0!=softwareDownload.productDownload&&""!=softwareDownload.productDownload.uri&&
(window.location.href=softwareDownload.productDownload.uri)},showProgress:!0,target:$(this)})})});$(function(){$(document).on("click",".modal-dismiss",function(){$(this).parents(".modal").hide();$(document).unbind("keydown mousewheel DOMMouseScroll");softwareDownload.eventTarget.focus()})});
$(function(){$(document).on("click","#feedback-send-button",function(a){a.preventDefault();a=softwareDownload.getValueOrNull("input:radio[name\x3dfeedback-question1-radio]:checked");var b=softwareDownload.getValueOrNull("input:radio[name\x3dfeedback-question2-radio]:checked"),g=$("#feedback-extra-comments").val(),h=!1;null===a?(softwareDownload.showError(!0,"#feedback-question1","#feedback-question1","feedback-question1-error"),h=!0):softwareDownload.showError(!1,"#feedback-question1","#feedback-question1",
"feedback-question1-error");null===b?(softwareDownload.showError(!0,"#feedback-question2","#feedback-question2","feedback-question2-error"),h=!0):softwareDownload.showError(!1,"#feedback-question2","#feedback-question2","feedback-question2-error");h?(null===a&&null===b&&$("#feedback-question1 ul li:nth-child(1) label input").focus(),null===a&&$("#feedback-question1 ul li:nth-child(1) label input").focus(),null===b&&null!==a&&$("#feedback-question2 ul li:nth-child(1) label input").focus()):(nodeId=
"SoftwareDownload_FeedbackSubmit",softwareDownload.renderContent({id:nodeId,query:{sessionId:softwareDownload.getSession(),qr1:a,qr2:b,qr3:g},callback:function(c){$("#feedback-action").addClass("has-success");$("#668657eb-b1ac-4c09-9105-1529f3534c81 :input").prop("disabled",!0);$("#feedback-send-button").remove()},showProgress:!1,target:$(this)}))})});
(function(a,b,g){a.AppInsights=a.AppInsights||{};a.AppInsights.getAppInsights=function(){var h=window.appInsights||function(c){function e(z){d[z]=function(){var r=arguments;d.queue.push(function(){d[z].apply(d,r)})}}var d={config:c},l=document,k=window,f=l.createElement("script"),m,u;f.src=c.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js";l.getElementsByTagName("script")[0].parentNode.appendChild(f);d.cookie=l.cookie;d.queue=[];for(m=["Event","Exception","Metric","PageView","Trace"];m.length;)e("track"+
m.pop());return e("setAuthenticatedUserContext"),e("clearAuthenticatedUserContext"),c.disableExceptionTracking||(m="onerror",e("_"+m),u=k[m],k[m]=function(z,r,x,w,t){var A=u&&u(z,r,x,w,t);return!0!==A&&d["_"+m](z,r,x,w,t),A}),d}({instrumentationKey:"4b6c76d0-4d71-4a6a-8a4a-870c27551af5"});return window.appInsights=h};a.AppInsights.getCustomEventProperties=function(h,c,e,d){var l="Not applicable";"undefined"!==typeof d&&(l=d);d=new Date;return{AzureDataCenter:"Not applicable",Category:h,CreatedDate:(new Date(d.getTime()-
6E4*d.getTimezoneOffset())).toISOString(),Configuration:"Not applicable",requestId:e,ServiceName:"Software Download",status:"Complete",tenantId:"Not applicable",contentOriginationCountry:"Not applicable",contentLanguage:c,contentItemCollection:"Not applicable",processId:"Not applicable",payloadId:"Not applicable",customData:l,locale:c,parentId:"Not applicable",CompletedDate:(new Date((new Date).getTime()-6E4*(new Date).getTimezoneOffset())).toISOString()}}})(window.softwareDownload=window.softwareDownload||
{},jQuery);
(function(a,b,g){function h(k,f){a:{for(var m in f)if(f.hasOwnProperty(m)&&m.toLowerCase()===k.toLowerCase()){f=f[m];break a}f=null}null!=f&&(k=window.location.href.replace(new RegExp(k,"i"),f),window.location.replace(k),a.redirection.isRedirecting=!0)}a.redirection=a.redirection||{};var c={windows8:"windows8ISO",windows10:"windows10ISO",vlacademicwindows10:"vlacademicwindows10iso"},e={windows8ISO:"windows8",windows10ISO:"windows10",vlacademicwindows10iso:"vlacademicwindows10"},d={},l=["Windows 11",
"Windows 10","Windows 8.1","Windows 8","Windows 7"];a.redirection.isRedirecting=!1;a.redirection.redirect=function(){a:{var k=window.location.pathname.split("/");for(var f=k.length-1;0<=f;f--)if(""!==k[f]){k=k[f];break a}k=""}h(k,d);f=a.userAttributes.getOs();f=f.name+" "+f.version;console.log("Redirect to OS Pages!!!");console.log("Device "+f.toString());-1==l.indexOf(f)?h(k,c):h(k,e)}})(window.softwareDownload=window.softwareDownload||{},jQuery);
(function(a,b,g){a.xbox=a.xbox||{};a.xbox.resetToOne=function(){a.xbox.unCheckOne();a.xbox.unCheckTwo();a.xbox.unCheckThree();a.xbox.showConfirmProductEdition();a.xbox.showConfirmSku3()};a.xbox.resetToTwo=function(){a.xbox.checkOne();a.xbox.unCheckTwo();a.xbox.unCheckThree();a.xbox.hideConfirmProductEdition();a.xbox.showConfirmSku3()};a.xbox.resetToThree=function(){a.xbox.checkOne();a.xbox.checkTwo();a.xbox.unCheckThree();a.xbox.hideConfirmProductEdition();a.xbox.hideConfirmSku3();b("#SDS_LanguageSelectionByProductEdition").parent().parent().css("display",
"block")};a.xbox.hideConfirmProductEdition=function(){null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()&&b("#submit-product-edition").addClass("x-hidden")};a.xbox.showConfirmProductEdition=function(){null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()&&b("#submit-product-edition").removeClass("x-hidden")};a.xbox.hideConfirmSku3=function(){null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()&&b("#submit-sku3").addClass("x-hidden")};a.xbox.showConfirmSku3=
function(){null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()&&b("#submit-sku3").removeClass("x-hidden")};a.xbox.checkOne=function(){null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()&&(b("#xbox_one_check").removeClass("x-hidden"),b("#xbox_one_number").addClass("x-hidden"))};a.xbox.unCheckOne=function(){null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()&&(b("#xbox_one_check").addClass("x-hidden"),b("#xbox_one_number").removeClass("x-hidden"))};a.xbox.checkTwo=
function(){null!=b("#xbox_two_check").val()&&null!=b("#xbox_two_number").val()&&(b("#xbox_two_check").removeClass("x-hidden"),b("#xbox_two_number").addClass("x-hidden"))};a.xbox.unCheckTwo=function(){null!=b("#xbox_two_check").val()&&null!=b("#xbox_two_number").val()&&(b("#xbox_two_check").addClass("x-hidden"),b("#xbox_two_number").removeClass("x-hidden"))};a.xbox.checkThree=function(){null!=b("#xbox_three_check").val()&&null!=b("#xbox_three_number").val()&&(b("#xbox_three_check").removeClass("x-hidden"),
b("#xbox_three_number").addClass("x-hidden"))};a.xbox.unCheckThree=function(){null!=b("#xbox_three_check").val()&&null!=b("#xbox_three_number").val()&&(b("#xbox_three_check").addClass("x-hidden"),b("#xbox_three_number").removeClass("x-hidden"))};a.xbox.xboxIconsPresent=function(){return null!=b("#xbox_one_check").val()&&null!=b("#xbox_one_number").val()}})(window.softwareDownload=window.softwareDownload||{},jQuery);